- name: Heroku
  apps:
  - name: gittip
  - name: gittip-access-dashboard
  - name: building-gittip-com
  - name: roobot-test
  - name: roobot-prod
- name: GitHub
  apps:
  - name: gittip/access-dashboard
  - name: gittip/building.gittip.com
  - name: gittip/Gittip-Everywhere
  - name: gittip/roobot
  - name: gittip/www.gittip.com
- name: Ally
  image:
  link:
  access:
  - whit537
- name: Balanced
  image:
  link:
  access:
  - bruceadams
  - clone1018
  - msherry
  - patcon
  - pjf
  - whit537
- name: Capital One
  image:
  link:
  access:
  - whit537
- name: DigitalOcean
  image:
  link:
  access:
  - whit537
  - rummik (root on gttp.co)
  - seanlinsley (deploy on gttp.co)
- name: Freshdesk
  image:
  link:
  access:
  - bruceadams (admin)
  - clone1018 (daypass)
  - patcon (admin)
  - pjf (daypass)
  - whit537 (admin)
- name: Gittip.com
  image:
  link:
  access:
  - clone1018
  - bruceadams
  - patcon
  - pjf
  - whit537
  - zwn
- name: Gittip LLC
  image:
  link:
  access:
  - whit537
- name: Google Analytics
  image:
  link:
  access:
  - abnor
  - clone1018
  - patcon
  - rummik
  - seanlinsley
  - whit537
- name: New Alliance
  image:
  link:
  access:
  - whit537
- name: PayPal
  image:
  link:
  access:
  - whit537
- name: Sentry
  image:
  link:
  access:
  - bruceadams
  - clone1018
  - patcon
  - rummik
  - seanlinsley
  - whit537
  - zwn
- name: SupportBee
  image:
  link:
  access:
  - bruceadams
  - whit537
- name: Tumblr
  image:
  link:
  access:
  - equis
  - heidigardner
  - whit537
- name: Twitter
  image:
  link:
  access:
  - whit537
